name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ "1.22", "1.23", ">=1.24" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
    - run: go vet ./...
    - run: go test "-coverprofile=coverage.txt" -covermode=atomic ./...
    - name: Upload Coverage Report
      if: ${{ github.event_name == 'push' && matrix.go-version == '1.23' }}
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        go install github.com/mattn/goveralls@latest
        goveralls -coverprofile=coverage.txt
